# Generated by Django 5.0.6 on 2024-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sliderimage_options_sliderimage_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='alt_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='title_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='nfqnk'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
